StuxGeek/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StuxGeek.Models
{
    public class LoginViewModel
    {
        [Required]
        public string Email { get; set; }

        [Required]
        public string Password { get; set; }
    }
}

StuxGeek/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StuxGeek.Models
{
    public class Post
    {

        public int PostId { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        public string Content { get; set; }

        [Required] //Meerdere categories
        public string Category { get; set; }
        
        public string Author { get; set; }

        [Required] //meerdere Tags
        public string Tag { get; set; }

        
        public DateTime PostDate { get; set; }
    }
}

StuxGeek/Models/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StuxGeek.Models
{
    public class RegisterViewModel
    {
        [Required]
        public string Username { get; set; }

        [Required]
        public string Email { get; set; }

        
        [Required]
        [Compare("Email")]
        [DisplayName("Repeat Email")]
        public string C_Email { get; set; }

        [Required]
        public string Password { get; set; }

        [Required]
        [Compare("Password")]
        [DisplayName("Repeat Password")]
        public string C_Password { get; set; }

        [Required]
        public DateTime TimeOfRegistration { get; set; }
    }
}

StuxGeek/Models/StuxGeekContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace StuxGeek.Models
{
    public class StuxGeekContext: DbContext
    {

        public StuxGeekContext()
        {
            Database.SetInitializer(new MigrateDatabaseToLatestVersion<StuxGeekContext, StuxGeek.Migrations.Configuration>());
        }

        public DbSet<User> Users { get; set; }
        public DbSet<Post> Posts { get; set; }
    }
}

StuxGeek/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StuxGeek.Models
{
    public class User
    {
        public int UserID { get; set; }

        [Required]
        public string Username { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public string Password { get; set; }

        [Required]
        public DateTime TimeOfRegistration { get; set; }
    }
}

StuxGeek/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StuxGeek.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }
    }
}

StuxGeek/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StuxGeek.Models;

namespace StuxGeek.Controllers
{
    public class HomeController : Controller
    {
        StuxGeekContext db = new StuxGeekContext();

        public ActionResult Index()
        {
            return View(db.Posts.ToList());
        }
    }
}

StuxGeek/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StuxGeek.Models;

namespace StuxGeek.Controllers
{
    public class PostController : Controller
    {

        StuxGeekContext db = new StuxGeekContext();

        [HttpGet]
        public ActionResult New()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public ActionResult New(Post post)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                post.PostDate = DateTime.Now;
                post.Author = User.Identity.Name;

                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult Manage()
        {

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpGet]
        [Route("post/read/{postTitle}")]
        public ActionResult Read(string postTitle)
        {
            Post post = db.Posts.FirstOrDefault(x => x.Title.Equals(postTitle.Replace("-"," ")));
            if (post != null)
            {
                return View(post);
            }
            else {
                return RedirectToAction("index", "home");
            }
            
        }

    }
}

StuxGeek/Controllers/SocialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StuxGeek.Controllers
{
    public class SocialController : Controller
    {
        // GET: Social
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Manage()
        {
            return View();
        }

    }
}

StuxGeek/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StuxGeek.Models;
using System.Web.Security;

namespace StuxGeek.Controllers
{
    public class UserController : Controller
    {

        StuxGeekContext db = new StuxGeekContext();

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(RegisterViewModel newUser)
        {

            if (db.Users.FirstOrDefault(x => x.Email.ToLower() == newUser.Email.ToLower()) != null)
            {
                ModelState.AddModelError("Email", "Email address already exists. Please enter a different email address.");
            }

            if (db.Users.FirstOrDefault(x => x.Username == newUser.Username) != null)
            {
                ModelState.AddModelError("Username", "Username address already exists. Please enter a different Username");
            }

            if (ModelState.IsValid) { 

                User user = new User();
                user.Username = newUser.Username;
                user.Password = newUser.Password;
                user.Email = newUser.Email;
                user.TimeOfRegistration = DateTime.Now;

                db.Users.Add(user);
                db.SaveChanges();

                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel login)
        {

            if (db.Users.FirstOrDefault(x => x.Email.ToLower() == login.Email.ToLower() && x.Password == login.Password) != null)
            {
                if (ModelState.IsValid)
                {
                    User user = db.Users.FirstOrDefault(x => x.Email.ToLower() == login.Email.ToLower() && x.Password == login.Password);                    
                    FormsAuthentication.SetAuthCookie(user.Username, false);

                    return RedirectToAction("Index", "Home");
                }
            }
            else 
            {
                ModelState.AddModelError("", "Invalid Credentials");
            }
            return View();
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index","Home");
        }

        public ActionResult LostPassword()
        {
            return View();
        }

    }
}

StuxGeek/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Admin Center</h2>

<div class="row padding-bot-1 padding-left-1 padding-right-1">
    <div class="col-xs-4">
        <div class="padding-right-half">
            <div class="row margin-bot-half" style="border: 1px solid black">
                <h4 class="text-center">Social Media</h4>
                <ul class="list-unstyled">
                    <li class="padding-left-1">@Html.ActionLink("Feeds", "Index", "Social")</li>
                </ul>
            </div>
            <div class="row margin-bot-half" style="border: 1px solid black">
                <h4 class="text-center">Posts</h4>
                <ul class="list-unstyled">
                    <li class="padding-left-1">@Html.ActionLink("New Post", "New", "Post")</li>
                    <li class="padding-left-1">@Html.ActionLink("Manage Posts", "Manage", "Post")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-xs-4">
        <div class="padding-right-half padding-left-half">
            <div class="row margin-bot-half" style="border: 1px solid black">
                <h4 class="text-center">Social Media</h4>
            </div>
            <div class="row margin-bot-half" style="border: 1px solid black">
                <h4 class="text-center">Other Ti</h4>
            </div>
        </div>
    </div>
    <div class="col-xs-4">
        <div class="padding-right-half padding-left-half">
            <div class="row margin-bot-half" style="border: 1px solid black">
                <h4 class="text-center">Social Media</h4>
            </div>
            <div class="row margin-bot-half" style="border: 1px solid black">
                <h4 class="text-center">Other Ti</h4>
            </div>
        </div>
    </div>
</div>

StuxGeek/Views/Home/Index.cshtml
@model List<StuxGeek.Models.Post>

<h2>Index</h2>
<div class="row padding-bot-1 padding-left-1 padding-right-1">
    <div class="col-xs-8">
        <div class="padding-right-half">
            @foreach (StuxGeek.Models.Post item in Model)
            {
                <a href="@Url.Action("Read", "Post", new { postTitle = item.Title.Replace(" ", "-") })">
                    <div class="row margin-bot-half" style="border: 1px solid black">
                        <div class="image-wrapper">
                            <img src="~/Content/Images/Mt_McKinley_wide_view_from_Kashwitna_Lake.jpg" class="img-responsive" alt="sometext" />
                            <h3>@item.Title</h3>
                        </div>
                    </div>
                </a>
            }   
        </div>
    </div>

    <div class="col-xs-4">
        <div class="padding-left-half">
            <div class="row margin-bot-half" style="border: 1px solid black">
                <div class="row">
                    <div class="col-xs-12">
                        Sidebar Item 1
                    </div>
                </div>
            </div>
            <div class="row margin-bot-half" style="border: 1px solid black">
                <div class="row">
                    <div class="col-xs-12">
                        Sidebar Item 2
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

StuxGeek/Views/Post/Manage.cshtml
@{
    ViewBag.Title = "Manage";
}

<h2>Manage</h2>

StuxGeek/Views/Post/New.cshtml
@model StuxGeek.Models.Post
@{
    ViewBag.Title = "New";
}

<h2>New Post</h2>

@using (Html.BeginForm())
{
    
    @Html.ValidationSummary()

    <div class="form-group">
        @Html.LabelFor(x => x.Title)
        @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Description)
        @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Content)
        @Html.TextBoxFor(x => x.Content, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Category)
        @Html.TextBoxFor(x => x.Category, new { @class = "form-control" })
    </div>
    
    <div class="form-group">
        @Html.LabelFor(x => x.Tag)
        @Html.TextBoxFor(x => x.Tag, new { @class = "form-control" })
    </div>

    <input type="submit" value="Submit Post" name="SubmitPost" class="btn btn-success form-control max" />
}

StuxGeek/Views/Post/Read.cshtml
@model StuxGeek.Models.Post

@{
    ViewBag.Title = "Read";
}

<h2>@Model.Title</h2>
<hr />
<p>@Model.Author</p>
<p>@Model.PostDate</p>
<hr />


<p><b>Description - </b>@Model.Description</p>

<p><b>Content - </b>@Model.Content</p>

<p><b>Category - </b>@Model.Category</p>

<p><b>Tag - </b>@Model.Tag</p>

StuxGeek/Views/Shared/_Layout.cshtml
@using System
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StuxGeek</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("StuxGeek", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">

                        @if (User.Identity.IsAuthenticated)
                        {
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@User.Identity.Name<span class="caret"></span></a>
                            <ul class="dropdown-menu inverse-dropdown">
                            <li>@Html.ActionLink("Admin Center", "Index", "Admin")</li>

                            <li role="separator" class="divider"></li>

                            <li>@Html.ActionLink("Logout", "Logout", "User")</li>
                        </ul>
                        }
                        else 
                        { 
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
                            <ul class="dropdown-menu inverse-dropdown">
                            <li>@Html.ActionLink("Login", "Login", "User")</li>
                            <li>@Html.ActionLink("Register", "Register", "User")</li>

                            <li role="separator" class="divider"></li>

                            <li>@Html.ActionLink("Forgot Password?", "LostPassword", "User")</li>
                        </ul>
                        }
                        

                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <!--
        <hr/>
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
        -->
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

StuxGeek/Views/Social/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Social Media</h2>

<div class="row padding-bot-1 padding-left-1 padding-right-1">
    <div class="col-xs-6">
        <div class="padding-right-half">
            <div class="row margin-bot-half" style="border: 1px solid black">
                <h4 class="text-center">Twitter</h4>
            </div>
            <div class="row margin-bot-half" style="border: 1px solid black">
                <h4 class="text-center"></h4>
            </div>
        </div>
    </div>
    <div class="col-xs-6">
        <div class="padding-right-half padding-left-half">
            <div class="row margin-bot-half" style="border: 1px solid black">
                <h4 class="text-center">Facebook</h4>
            </div>
            <div class="row margin-bot-half" style="border: 1px solid black">
                <h4 class="text-center"></h4>
            </div>
        </div>
    </div>
</div>

StuxGeek/Views/Social/Manage.cshtml
@{
    ViewBag.Title = "Manage";
}

<h2>Manage</h2>

StuxGeek/Views/User/Login.cshtml
@model StuxGeek.Models.LoginViewModel

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary()

    <div class="form-group">
        @Html.LabelFor(x => x.Email)
        @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Password)
        @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
    </div>

    <input type="submit" value="Register" name="register" class="btn btn-success form-control max" />
}

StuxGeek/Views/User/LostPassword.cshtml
@{
    ViewBag.Title = "LostPassword";
}

<h2>LostPassword</h2>

StuxGeek/Views/User/Register.cshtml
@model StuxGeek.Models.RegisterViewModel

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary()

    <div class="form-group">
        @Html.LabelFor(x => x.Username)
        @Html.TextBoxFor(x => x.Username, new {@class = "form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Email)
        @Html.TextBoxFor(x => x.Email, new {@class = "form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.C_Email)
        @Html.TextBoxFor(x => x.C_Email, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Password)
        @Html.PasswordFor(x => x.Password, new {@class = "form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.C_Password)
        @Html.PasswordFor(x => x.C_Password, new { @class = "form-control" })
    </div>

    <input type="submit" value="Register" name="register" class="btn btn-success form-control max"/>
}